// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEYB4yXF_HNDoPFe0xbyRP3mIECB-5tRU',
    appId: '1:1069885073793:web:0e344de33aa26863ce6080',
    messagingSenderId: '1069885073793',
    projectId: 'allosa-vinyl',
    authDomain: 'allosa-vinyl.firebaseapp.com',
    databaseURL: 'https://allosa-vinyl-default-rtdb.firebaseio.com',
    storageBucket: 'allosa-vinyl.firebasestorage.app',
    measurementId: 'G-Z5Y51ZG4T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_DaS6a7vBhfl691bgD-lCBqFeES21FSk',
    appId: '1:1069885073793:android:0cb3fc1d3aeb4b34ce6080',
    messagingSenderId: '1069885073793',
    projectId: 'allosa-vinyl',
    databaseURL: 'https://allosa-vinyl-default-rtdb.firebaseio.com',
    storageBucket: 'allosa-vinyl.firebasestorage.app',
  );

}